version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: NewCrud
      MYSQL_USER: jepierre
      MYSQL_PASSWORD: mamateamo123
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - my-network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - my-network
      
  new-crud:
    image: newcrud
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - my-network
    depends_on:
      - mysql
volumes:
  mysql-data:

networks:
  my-network:
    driver: bridge
